config/routes.rb
Rails.application.routes.draw do
  root 'store#index', as: 'store_index'

  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'sessions/create'
  get 'sessions/destroy'
  resources :users
  resources :orders
  resources :line_items
  resources :carts
  resources :users
  
  resources :products do
    get :who_bought, on: :member
  end

  scope '(:locale)' do
    resources :orders
    resources :line_items
    resources :carts
    root 'store#index', as: 'store', via: :all
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Depot</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script type="text/javascript">
    I18n.defaultLocale = "<%= I18n.default_locale %>";
    I18n.locale        = "<%= I18n.locale %>";
  </script>
</head>

<body>
  <header class="main">
    <%= image_tag 'logo.svg', alt: 'The Pragmatic Bookshelf', size: '60x60' %>
    <h1><%= @page_title %></h1>
  </header>
  <section class="content">
    <nav class="side_nav">

      <div id="cart" class="carts">
        <%= render_if @cart && @cart.line_items.any?, @cart %>
      </div>

      <ul>
        <li><a href="/"><%= t('.home') %></a></li>
        <li><a href="/questions"><%= t('.questions') %></a></li>
        <li><a href="/news"><%= t('.news') %></a></li>
        <li><a href="/contact"><%= t('.contact') %></a></li>
        <li><%=Time.now.year%></li>
      </ul>
      <% if session[:user_id] %>
        <nav class="logged_in_nav">
          <ul>
            <li><%= link_to 'Orders', orders_path %></li>
            <li><%= link_to 'Products', products_path %></li>
            <li><%= link_to 'Users', users_path %></li>
            <li><%= button_to 'Logout', logout_path, method: :delete %></li>
          </ul>
        </nav>
      <% end %>
    </nav>
    <main class='<%= controller.controller_name %>'>
        <%= yield %>
    </main>

  </section>

</body>

</html>